export type Product = {
  slug: string;
  name: string;
  line: string;
  category: "Perfumes" | "Perfumes Árabes" | "Cabelo";
  price: number;
  oldPrice?: number;
  image: string;
  badge?: string;
  description: string;
  notes?: string[];
  size: string;
};

export const products: Product[] = [
  {
    slug: "212-vip-black",
    name: "212 VIP Black",
    line: "Carolina Herrera · Eau de Parfum",
    category: "Perfumes",
    price: 549,
    image: "https://fimgs.net/mdimg/perfume/375x500.46259.jpg",
    badge: "Mais vendido",
    description: "Intenso, jovem e noturno. Uma fragrância masculina de presença, com abertura aromática e fundo envolvente para noites marcantes.",
    notes: ["Absinto", "Lavanda", "Almíscar negro"],
    size: "100 ml",
  },
  {
    slug: "212-men-nyc",
    name: "212 Men NYC",
    line: "Carolina Herrera · Eau de Toilette",
    category: "Perfumes",
    price: 499,
    image: "https://fimgs.net/mdimg/perfume/375x500.258.jpg",
    badge: "Clássico",
    description: "Fresco, urbano e elegante. Um perfume masculino versátil para trabalho, encontros e rotina, com assinatura limpa e amadeirada.",
    notes: ["Folhas verdes", "Gengibre", "Sândalo"],
    size: "100 ml",
  },
  {
    slug: "one-million",
    name: "1 Million",
    line: "Rabanne · Eau de Toilette",
    category: "Perfumes",
    price: 579,
    image: "https://fimgs.net/mdimg/perfume/375x500.1998.jpg",
    badge: "Ícone",
    description: "Quente, especiado e inconfundível. 1 Million combina impacto e sensualidade em uma assinatura masculina feita para chamar atenção.",
    notes: ["Mandarina", "Canela", "Couro"],
    size: "100 ml",
  },
  {
    slug: "one-million-elixir",
    name: "1 Million Elixir",
    line: "Rabanne · Parfum Intense",
    category: "Perfumes",
    price: 699,
    image: "https://fimgs.net/mdimg/perfume/375x500.68553.jpg",
    badge: "Alta intensidade",
    description: "Uma leitura mais profunda e concentrada do ícone dourado, com frutas, rosa e madeiras em uma base doce de longa duração.",
    notes: ["Maçã", "Rosa damascena", "Baunilha"],
    size: "100 ml",
  },
  {
    slug: "asad-lattafa",
    name: "Asad",
    line: "Lattafa · Eau de Parfum",
    category: "Perfumes Árabes",
    price: 249,
    image: "https://fimgs.net/mdimg/perfume/375x500.72821.jpg",
    badge: "Árabe mais vendido",
    description: "Potente e especiado, Asad entrega uma combinação quente de pimenta, tabaco e baunilha com excelente presença noturna.",
    notes: ["Pimenta preta", "Tabaco", "Baunilha"],
    size: "100 ml",
  },
  {
    slug: "club-de-nuit-intense-man",
    name: "Club de Nuit Intense Man",
    line: "Armaf · Eau de Toilette",
    category: "Perfumes Árabes",
    price: 299,
    image: "https://fimgs.net/mdimg/perfume/375x500.34696.jpg",
    badge: "Projeção alta",
    description: "Cítrico na saída e amadeirado no fundo, é uma das escolhas árabes masculinas mais conhecidas para quem busca projeção e versatilidade.",
    notes: ["Limão", "Abacaxi", "Bétula"],
    size: "105 ml",
  },
  {
    slug: "afnan-9pm",
    name: "9PM",
    line: "Afnan · Eau de Parfum",
    category: "Perfumes Árabes",
    price: 289,
    image: "https://fimgs.net/mdimg/perfume/375x500.65414.jpg",
    badge: "Para a noite",
    description: "Doce, marcante e sedutor. Uma combinação de maçã, canela e baunilha feita especialmente para festas e encontros noturnos.",
    notes: ["Maçã", "Canela", "Baunilha"],
    size: "100 ml",
  },
  {
    slug: "fakhar-black",
    name: "Fakhar Black",
    line: "Lattafa · Eau de Parfum",
    category: "Perfumes Árabes",
    price: 239,
    image: "https://fimgs.net/mdimg/perfume/375x500.70465.jpg",
    description: "Aromático, fresco e masculino, com especiarias, lavanda e um fundo amadeirado elegante para o uso diário.",
    notes: ["Maçã", "Lavanda", "Cedro"],
    size: "100 ml",
  },
  {
    slug: "macho-landia-sculp-mate",
    name: "Pomada Fibrosa Sculp Mate",
    line: "Macho-Lândia · Fixação matte",
    category: "Cabelo",
    price: 75.9,
    image: "https://cdn.shopify.com/s/files/1/0772/9122/5338/files/Pomada1x1site.png?v=1773688068",
    badge: "Produto real",
    description: "Pomada fibrosa masculina para criar textura e definição com acabamento matte. Produto vendido pela Macho-Lândia.",
    size: "86 g",
  },
  {
    slug: "macho-landia-cronos-extreme",
    name: "Cera Matte Extreme Cronos",
    line: "Macho-Lândia · Fixação extrema",
    category: "Cabelo",
    price: 99.9,
    image: "https://cdn.shopify.com/s/files/1/0772/9122/5338/files/CeraCronos41x1.png?v=1773687919",
    badge: "Fixação extrema",
    description: "Cera masculina de alta fixação e acabamento seco para penteados que precisam permanecer no lugar.",
    size: "86 g",
  },
  {
    slug: "macho-landia-shampoo-deep-ice",
    name: "Shampoo Deep Ice Triplo XXX",
    line: "Macho-Lândia · Limpeza refrescante",
    category: "Cabelo",
    price: 79.9,
    image: "https://cdn.shopify.com/s/files/1/0772/9122/5338/files/S_BDeepIce11x1site.png?v=1773685404",
    description: "Shampoo masculino Deep Ice para limpeza intensa e sensação refrescante no cuidado diário.",
    size: "250 ml",
  },
  {
    slug: "jaboque-pomada-matte",
    name: "Pomada Efeito Matte",
    line: "Jaboque Brasil · Acabamento natural",
    category: "Cabelo",
    price: 57.9,
    image: "https://cdn.awsli.com.br/300x300/600/600897/produto/401164779/0abd21b59e7b4e8dbaf359e1d404986a-zh54z0ua5m.png",
    badge: "Produto real",
    description: "Pomada masculina Jaboque com efeito matte e acabamento natural para modelar sem brilho excessivo.",
    size: "80 g",
  },
  {
    slug: "jaboque-pomada-nuvem",
    name: "Pomada Nuvem",
    line: "Jaboque Brasil · Fixação média",
    category: "Cabelo",
    price: 57.9,
    image: "https://cdn.awsli.com.br/300x300/600/600897/produto/375494460/captura-de-tela-2025-10-13-a-s-18-00-14-4k11wgd9sx.png",
    description: "Pomada finalizadora de textura leve, fragrância suave e fixação média para um visual natural.",
    size: "80 g",
  },
  {
    slug: "jaboque-grooming-modelador",
    name: "Grooming Modelador",
    line: "Jaboque Brasil · Fixação leve",
    category: "Cabelo",
    price: 57.9,
    image: "https://cdn.awsli.com.br/300x300/600/600897/produto/374591461/grooming-cabelo-masculino-jaboque-240ml-0jhbuj0q85.png",
    description: "Modelador masculino de fixação leve para alinhar, hidratar e controlar o cabelo sem pesar.",
    size: "240 ml",
  },
  {
    slug: "jaboque-leave-in-antifrizz",
    name: "Leave-In Anti-Frizz",
    line: "Jaboque Brasil · Hidratação",
    category: "Cabelo",
    price: 69.9,
    image: "https://cdn.awsli.com.br/300x300/600/600897/produto/365310969/leave-in-cabelo-masculino-jaboque-1-k10b79qr1c.png",
    description: "Leave-in masculino para hidratação, controle de frizz e acabamento leve no dia a dia.",
    size: "240 ml",
  },
];

export const money = (value: number) =>
  new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);

export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
